version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo install phase started on `date`
      - python --version
      - 'curl -O https://bootstrap.pypa.io/get-pip.py'
      - python3 get-pip.py
      - pip install --upgrade pip
      - pip3 install -U setuptools
      - add-apt-repository main
      - add-apt-repository universe
      - add-apt-repository restricted
      - add-apt-repository multiverse
      - apt update
      - apt-get install -y unixodbc-dev
      - apt-get install python3-mysql.connector
      - apt-get install jq
      - find ./ -type f -name "requirements_for_testing.txt" -exec pip3 install -r  "{}"  \;
      - aws secretsmanager get-secret-value --secret-id github/code-pipeline/full-access-token > git_hub_access_token.json
      - GIT_HUB_ACCESS_TOKEN=$(jq -r '.SecretString' git_hub_access_token.json)
      - git clone https://$GIT_HUB_ACCESS_TOKEN@github.com/tasq-inc/tasq-codepipeline-repo.git
      - cp tasq-codepipeline-repo/requirements.txt .
      - pip3 install -r requirements.txt
      - CURRENT_REPO="$(python3 tasq-codepipeline-repo/get_repo_name.py)"
      - echo $CURRENT_REPO
      - git clone https://$GIT_HUB_ACCESS_TOKEN@github.com/tasq-inc/$CURRENT_REPO.git

  build:
    commands:
      - echo Build phase started on `date`
      - cd $CURRENT_REPO
      - BRANCH_NAME_STRING=$(git name-rev --name-only --exclude=tags/* $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - BRANCH_NAME="${BRANCH_NAME_STRING##*/}"
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
