Resources:
    ApiGatewayTokensTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "TokenID"
            AttributeType: S
          - AttributeName: "Username"
            AttributeType: S
          - AttributeName: "AccessToken"
            AttributeType: S
          - AttributeName: "time"
            AttributeType: S
        KeySchema: #required
          - AttributeName: "TokenID"
            KeyType: HASH
          - AttributeName: "time"
            KeyType: RANGE
        GlobalSecondaryIndexes:
         - IndexName: User-index
           KeySchema:
           - AttributeName: "Username"
             KeyType: HASH
           Projection:
             ProjectionType: ALL
         - IndexName: AccessToken-index
           KeySchema:
           - AttributeName: "AccessToken"
             KeyType: HASH
           Projection:
             ProjectionType: ALL

  
Outputs:
  ApiGatewayTokensTable:
    Description: DynamoDB table for predictions jobs
    Value: !Ref 'ApiGatewayTokensTable'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'ApiGatewayTokensTable' ] ]
